require "fileutils"
require "pathname"
require "rake"

extend Rake::DSL

module NitroKit
  module CssBundle
    ROOT = Pathname.new(File.expand_path("../..", __dir__))
    SOURCE_ROOT = ROOT.join("src/stylesheets/nitro_kit")
    OUTPUT = ROOT.join("app/assets/stylesheets/nitro_kit.css")
    FOUNDATION_SOURCES = %w[ layers.css tokens.css reset.css ].freeze
    BANNER = <<~CSS.freeze
      /*
       * Nitro Kit 2.0
       * Generated by `rake nitro_kit:css:build`. Do not edit directly.
       */
    CSS

    module_function

    def source_files
      foundation_sources + component_sources
    end

    def compile
      sections = source_files.map do |path|
        <<~CSS.rstrip
          /* Source: #{path.relative_path_from(ROOT)} */
          #{path.read.rstrip}
        CSS
      end

      ([ BANNER.rstrip ] + sections).join("\n\n") + "\n"
    end

    def write
      css = compile

      return false if OUTPUT.exist? && OUTPUT.read == css

      FileUtils.mkdir_p(OUTPUT.dirname)
      OUTPUT.write(css)
      true
    end

    def current?
      OUTPUT.exist? && OUTPUT.read == compile
    end

    def foundation_sources
      FOUNDATION_SOURCES.map { |name| SOURCE_ROOT.join(name) }
    end

    def component_sources
      SOURCE_ROOT.glob("components/**/*.css").sort
    end
  end
end

namespace :nitro_kit do
  namespace :css do
    desc "Build the committed Nitro Kit stylesheet"
    task :build do
      if NitroKit::CssBundle.write
        puts "Wrote #{NitroKit::CssBundle::OUTPUT.relative_path_from(NitroKit::CssBundle::ROOT)}"
      else
        puts "Nitro Kit CSS is already up to date"
      end
    end

    desc "Check that the committed Nitro Kit stylesheet is current"
    task :check do
      next if NitroKit::CssBundle.current?

      abort "Nitro Kit CSS is out of date. Run `rake nitro_kit:css:build`."
    end
  end
end
