version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
