class Game
  def self.all
    [
      ["Assetto Corsa", "assetto_corsa"],
      ["Automobilista", "automobilista"],
      ["Blur", "blur"],
      ["Burnout Paradise", "burnout_paradise"],
      ["Crash Team Racing", "crash_team_racing"],
      ["Crazy Taxi", "crazy_taxi"],
      ["Daytona USA", "daytona_usa"],
      ["Dirt Rally", "dirt_rally"],
      ["Driver", "driver"],
      ["Excitebike", "excitebike"],
      ["Extreme-G", "extreme_g"],
      ["F-Zero", "f_zero"],
      ["F1 23", "f1_23"],
      ["FlatOut", "flatout"],
      ["Forza Horizon", "forza_horizon"],
      ["Gran Turismo", "gran_turismo"],
      ["Hot Wheels Unleashed", "hot_wheels_unleashed"],
      ["Hydro Thunder", "hydro_thunder"],
      ["KartRider", "kartrider"],
      ["Mario Kart", "mario_kart"],
      ["Midnight Club", "midnight_club"],
      ["MotoGP", "motogp"],
      ["MotorStorm", "motorstorm"],
      ["Need for Speed", "need_for_speed"],
      ["OutRun", "outrun"],
      ["Pole Position", "pole_position"],
      ["Project Cars", "project_cars"],
      ["Pure", "pure"],
      ["Race Driver: Grid", "grid"],
      ["RalliSport Challenge", "rallisport_challenge"],
      ["Ridge Racer", "ridge_racer"],
      ["Road Rash", "road_rash"],
      ["Rocket League", "rocket_league"],
      ["Sega Rally Championship", "sega_rally"],
      ["SnowRunner", "snowrunner"],
      ["Speed Devils", "speed_devils"],
      ["Split/Second", "split_second"],
      ["Stuntman", "stuntman"],
      ["Super Hang-On", "super_hang_on"],
      ["Super Off Road", "super_off_road"],
      ["Test Drive Unlimited", "test_drive_unlimited"],
      ["The Crew", "the_crew"],
      ["Tourist Trophy", "tourist_trophy"],
      ["TrackMania", "trackmania"],
      ["V-Rally", "v_rally"],
      ["Wave Race", "wave_race"],
      ["Wipeout", "wipeout"],
      ["Wreckfest", "wreckfest"],
      ["iRacing", "iracing"]
    ]
  end
end
